# GENERATED by newman.py -- do not edit by hand.
# The Newman corpus: id=Output.pdf and id:tocdepth:"HTML title".

NEWMAN_PDFS = \
  grammar=Grammar_of_Assent.pdf

NEWMAN_HTML = \
  grammar:2:"An Essay in Aid of a Grammar of Assent"
