# GENERATED by schaff.py -- do not edit by hand.
# The complete Schaff corpus: id=Output.pdf and id:tocdepth:"HTML title".

SCHAFF_PDFS = \
  anf01=Ante-Nicene_Fathers_Vol_1.pdf \
  anf02=Ante-Nicene_Fathers_Vol_2.pdf \
  anf03=Ante-Nicene_Fathers_Vol_3.pdf \
  anf04=Ante-Nicene_Fathers_Vol_4.pdf \
  anf05=Ante-Nicene_Fathers_Vol_5.pdf \
  anf06=Ante-Nicene_Fathers_Vol_6.pdf \
  anf07=Ante-Nicene_Fathers_Vol_7.pdf \
  anf08=Ante-Nicene_Fathers_Vol_8.pdf \
  anf09=Ante-Nicene_Fathers_Vol_9.pdf \
  npnf101=Nicene_and_Post-Nicene_Fathers_Series_1_Vol_1.pdf \
  npnf102=Nicene_and_Post-Nicene_Fathers_Series_1_Vol_2.pdf \
  npnf103=Nicene_and_Post-Nicene_Fathers_Series_1_Vol_3.pdf \
  npnf104=Nicene_and_Post-Nicene_Fathers_Series_1_Vol_4.pdf \
  npnf105=Nicene_and_Post-Nicene_Fathers_Series_1_Vol_5.pdf \
  npnf106=Nicene_and_Post-Nicene_Fathers_Series_1_Vol_6.pdf \
  npnf107=Nicene_and_Post-Nicene_Fathers_Series_1_Vol_7.pdf \
  npnf108=Nicene_and_Post-Nicene_Fathers_Series_1_Vol_8.pdf \
  npnf109=Nicene_and_Post-Nicene_Fathers_Series_1_Vol_9.pdf \
  npnf110=Nicene_and_Post-Nicene_Fathers_Series_1_Vol_10.pdf \
  npnf111=Nicene_and_Post-Nicene_Fathers_Series_1_Vol_11.pdf \
  npnf112=Nicene_and_Post-Nicene_Fathers_Series_1_Vol_12.pdf \
  npnf113=Nicene_and_Post-Nicene_Fathers_Series_1_Vol_13.pdf \
  npnf114=Nicene_and_Post-Nicene_Fathers_Series_1_Vol_14.pdf \
  npnf201=Nicene_and_Post-Nicene_Fathers_Series_2_Vol_1.pdf \
  npnf202=Nicene_and_Post-Nicene_Fathers_Series_2_Vol_2.pdf \
  npnf203=Nicene_and_Post-Nicene_Fathers_Series_2_Vol_3.pdf \
  npnf204=Nicene_and_Post-Nicene_Fathers_Series_2_Vol_4.pdf \
  npnf205=Nicene_and_Post-Nicene_Fathers_Series_2_Vol_5.pdf \
  npnf206=Nicene_and_Post-Nicene_Fathers_Series_2_Vol_6.pdf \
  npnf207=Nicene_and_Post-Nicene_Fathers_Series_2_Vol_7.pdf \
  npnf208=Nicene_and_Post-Nicene_Fathers_Series_2_Vol_8.pdf \
  npnf209=Nicene_and_Post-Nicene_Fathers_Series_2_Vol_9.pdf \
  npnf210=Nicene_and_Post-Nicene_Fathers_Series_2_Vol_10.pdf \
  npnf211=Nicene_and_Post-Nicene_Fathers_Series_2_Vol_11.pdf \
  npnf212=Nicene_and_Post-Nicene_Fathers_Series_2_Vol_12.pdf \
  npnf213=Nicene_and_Post-Nicene_Fathers_Series_2_Vol_13.pdf

SCHAFF_HTML = \
  anf01:2:"Ante-Nicene Fathers, Vol. I: The Apostolic Fathers with Justin Martyr and Irenæus" \
  anf02:2:"Ante-Nicene Fathers, Vol. II: Fathers of the Second Century" \
  anf03:2:"Ante-Nicene Fathers, Vol. III: Latin Christianity: Its Founder, Tertullian" \
  anf04:2:"Ante-Nicene Fathers, Vol. IV: Fathers of the Third Century" \
  anf05:2:"Ante-Nicene Fathers, Vol. V: Fathers of the Third Century" \
  anf06:2:"Ante-Nicene Fathers, Vol. VI: Fathers of the Third Century" \
  anf07:2:"Ante-Nicene Fathers, Vol. VII: Fathers of the Third and Fourth Centuries" \
  anf08:2:"Ante-Nicene Fathers, Vol. VIII: The Twelve Patriarchs, Excerpts and Epistles, and the Ancient Remains" \
  anf09:2:"Ante-Nicene Fathers, Vol. IX: Recently Discovered Additions, with Origen's Commentaries" \
  npnf101:2:"Nicene and Post-Nicene Fathers, First Series, Vol. I: Prolegomena: St. Augustine's Life and Work, the Confessions, and the Letters" \
  npnf102:2:"Nicene and Post-Nicene Fathers, First Series, Vol. II: St. Augustine: The City of God and On Christian Doctrine" \
  npnf103:2:"Nicene and Post-Nicene Fathers, First Series, Vol. III: St. Augustine: On the Holy Trinity, and the Doctrinal and Moral Treatises" \
  npnf104:2:"Nicene and Post-Nicene Fathers, First Series, Vol. IV: St. Augustine: The Anti-Manichaean and Anti-Donatist Writings" \
  npnf105:2:"Nicene and Post-Nicene Fathers, First Series, Vol. V: St. Augustine: The Anti-Pelagian Writings" \
  npnf106:2:"Nicene and Post-Nicene Fathers, First Series, Vol. VI: St. Augustine: Sermon on the Mount, Harmony of the Gospels, and Homilies on the Gospels" \
  npnf107:2:"Nicene and Post-Nicene Fathers, First Series, Vol. VII: St. Augustine: Homilies on the Gospel of John, the First Epistle of John, and the Soliloquies" \
  npnf108:2:"Nicene and Post-Nicene Fathers, First Series, Vol. VIII: St. Augustine: Expositions on the Book of Psalms" \
  npnf109:2:"Nicene and Post-Nicene Fathers, First Series, Vol. IX: St. Chrysostom: On the Priesthood, Ascetic Treatises, Select Homilies and Letters, and Homilies on the Statutes" \
  npnf110:2:"Nicene and Post-Nicene Fathers, First Series, Vol. X: St. Chrysostom: Homilies on the Gospel of St. Matthew" \
  npnf111:2:"Nicene and Post-Nicene Fathers, First Series, Vol. XI: St. Chrysostom: Homilies on the Acts of the Apostles and the Epistle to the Romans" \
  npnf112:2:"Nicene and Post-Nicene Fathers, First Series, Vol. XII: St. Chrysostom: Homilies on First and Second Corinthians" \
  npnf113:2:"Nicene and Post-Nicene Fathers, First Series, Vol. XIII: St. Chrysostom: Homilies on the Epistles to the Galatians through Philemon" \
  npnf114:2:"Nicene and Post-Nicene Fathers, First Series, Vol. XIV: St. Chrysostom: Homilies on the Gospel of St. John and the Epistle to the Hebrews" \
  npnf201:2:"Nicene and Post-Nicene Fathers, Second Series, Vol. I: Eusebius: Church History, Life of Constantine, and Oration in Praise of Constantine" \
  npnf202:2:"Nicene and Post-Nicene Fathers, Second Series, Vol. II: Socrates and Sozomenus: Ecclesiastical Histories" \
  npnf203:2:"Nicene and Post-Nicene Fathers, Second Series, Vol. III: Theodoret, Jerome and Gennadius, Rufinus and Jerome" \
  npnf204:2:"Nicene and Post-Nicene Fathers, Second Series, Vol. IV: Athanasius: Select Works and Letters" \
  npnf205:2:"Nicene and Post-Nicene Fathers, Second Series, Vol. V: Gregory of Nyssa: Dogmatic Treatises, and Select Writings and Letters" \
  npnf206:2:"Nicene and Post-Nicene Fathers, Second Series, Vol. VI: Jerome: Letters and Select Works" \
  npnf207:2:"Nicene and Post-Nicene Fathers, Second Series, Vol. VII: Cyril of Jerusalem and Gregory Nazianzen" \
  npnf208:2:"Nicene and Post-Nicene Fathers, Second Series, Vol. VIII: Basil: Letters and Select Works" \
  npnf209:2:"Nicene and Post-Nicene Fathers, Second Series, Vol. IX: Hilary of Poitiers, and John of Damascus" \
  npnf210:2:"Nicene and Post-Nicene Fathers, Second Series, Vol. X: Ambrose: Select Works and Letters" \
  npnf211:2:"Nicene and Post-Nicene Fathers, Second Series, Vol. XI: Sulpitius Severus, Vincent of Lérins, and John Cassian" \
  npnf212:2:"Nicene and Post-Nicene Fathers, Second Series, Vol. XII: Leo the Great and Gregory the Great" \
  npnf213:2:"Nicene and Post-Nicene Fathers, Second Series, Vol. XIII: Gregory the Great (Part II), Ephraim Syrus, and Aphrahat"
