#!/usr/bin/env python3
"""scripts/infra_index.py --check | --write | --wrap FILE — the infrastructure
log's index and its rules (P2-4 of the 2026-09-16 review).

The long-form reference lives as dated passages in docs/architecture/log/
YYYY-MM.md — one file per month, a passage a bullet (or a paragraph) that
opens with a **bold lead-in**, grouped under `## <section>` headings. The
index of every lead-in, by section, is GENERATED into
docs/architecture/INFRASTRUCTURE.md between the two marker lines below, so no
two agents ever conflict on an index line again: append your passage to the
current month's file under its section heading, then run `--write`.

  --check      exit 1 when the committed index differs from the generated one,
               a lead-in is duplicated, a passage stands under no heading, or a
               prose line in a log file is longer than 100 columns (tests/py/
               test_infra_index.py runs this)
  --write      regenerate the index block in INFRASTRUCTURE.md
  --wrap FILE  reflow FILE's long prose lines to 100 columns (bullets keep a
               two-space hanging indent); code spans may break across lines,
               which Markdown allows"""
import glob
import os
import re
import sys
import textwrap

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOG = os.path.join(ROOT, 'docs', 'architecture', 'log')
INDEX = os.path.join(ROOT, 'docs', 'architecture', 'INFRASTRUCTURE.md')
START = '<!-- infra-index:start (generated by scripts/infra_index.py --write; do not edit by hand) -->'
END = '<!-- infra-index:end -->'
WIDTH = 100
# the sections in their canonical order (the order the old single file had); an unknown one goes last
SECTION_ORDER = [
    'Hosting and delivery',
    'Build system',
    'The PureScript application layer',
    'Testing policy',
    'Verifying the live site (headless browser)',
    'Infrastructure as code (Terraform, 2026-09-08)',
    'Cloudflare Workers (dynamic backend)',
]
LEAD = re.compile(r'^(?:- )?\*\*(.+?)\*\*', re.S)


def log_files():
    return sorted(glob.glob(os.path.join(LOG, '*.md')))


def passages(path):
    """(section, lead-in, line) for every passage in one log file; problems as
    sentences. A passage is a block that opens with a bold lead-in; blocks
    without one attach to the passage before them."""
    out, problems = [], []
    section = None
    with open(path, encoding='utf-8') as f:
        lines = f.read().split('\n')
    prev_blank = True
    for i, ln in enumerate(lines, start=1):
        if ln.startswith('## '):
            section = ln[3:].strip()
        elif prev_blank and (ln.startswith('**') or ln.startswith('- **')):
            # a wrapped lead-in closes on a later line of the same block: read up to six
            m = LEAD.match(' '.join(x.strip() for x in lines[i - 1:i + 6]))
            if not m:
                problems.append('%s:%d: a bold opening with no closing ** within six lines' % (os.path.relpath(path, ROOT), i))
            elif section is None:
                problems.append('%s:%d: the passage "%s" stands under no ## section heading' % (os.path.relpath(path, ROOT), i, m.group(1)[:50]))
            else:
                out.append((section, ' '.join(m.group(1).split()), i))
        prev_blank = (ln.strip() == '')
    return out, problems


def long_prose_lines(path):
    """Prose lines over WIDTH columns (code fences, tables and indented code are exempt)."""
    out = []
    fence = False
    with open(path, encoding='utf-8') as f:
        for i, ln in enumerate(f.read().split('\n'), start=1):
            if ln.startswith('```'):
                fence = not fence
                continue
            if fence or ln.startswith('|') or ln.startswith('    ') or ln.startswith('http'):
                continue
            if len(ln) > WIDTH and ' ' in ln.strip():
                out.append('%s:%d: %d columns' % (os.path.relpath(path, ROOT), i, len(ln)))
    return out


def render_index():
    by_section = {}
    problems = []
    seen = {}
    for path in log_files():
        rel = os.path.relpath(path, os.path.dirname(INDEX))
        ps, probs = passages(path)
        problems += probs
        for section, lead, line in ps:
            if lead in seen:
                problems.append('duplicate lead-in "%s" (%s and %s)' % (lead[:60], seen[lead], rel + ':' + str(line)))
            seen[lead] = rel + ':' + str(line)
            by_section.setdefault(section, []).append((lead, rel))
        problems += long_prose_lines(path)
    order = SECTION_ORDER + sorted(s for s in by_section if s not in SECTION_ORDER)
    out = [START, '', '## Index of the passages (by section; each names its month\'s file — grep the bold lead-in there)', '']
    for section in order:
        if section not in by_section:
            continue
        out.append('### ' + section)
        out.append('')
        for lead, rel in by_section[section]:
            out.append('- **%s** — `%s`' % (lead, rel))
        out.append('')
    out.append(END)
    return '\n'.join(out), problems


def split_index(text):
    i, j = text.find(START), text.find(END)
    if i < 0 or j < 0 or j < i:
        return None
    return text[:i], text[i:j + len(END)], text[j + len(END):]


def check():
    rendered, problems = render_index()
    with open(INDEX, encoding='utf-8') as f:
        text = f.read()
    parts = split_index(text)
    if parts is None:
        problems.append('INFRASTRUCTURE.md has no index markers')
    elif parts[1] != rendered:
        problems.append('INFRASTRUCTURE.md\'s index is stale — run scripts/infra_index.py --write')
    return problems


def write():
    rendered, problems = render_index()
    with open(INDEX, encoding='utf-8') as f:
        text = f.read()
    parts = split_index(text)
    if parts is None:
        text = text.rstrip('\n') + '\n\n' + rendered + '\n'
    else:
        text = parts[0] + rendered + parts[2]
    with open(INDEX, 'w', encoding='utf-8') as f:
        f.write(text)
    return problems


def wrap_text(text):
    """Reflow long prose lines; blank lines, headings, fences, tables and code stay."""
    out = []
    fence = False
    for ln in text.split('\n'):
        if ln.startswith('```'):
            fence = not fence
            out.append(ln)
            continue
        if fence or len(ln) <= WIDTH or ln.startswith('|') or ln.startswith('    ') or ln.startswith('#'):
            out.append(ln)
            continue
        indent = '  ' if ln.startswith('- ') else ''
        out.extend(textwrap.fill(ln, width=WIDTH, break_long_words=False, break_on_hyphens=False,
                                 subsequent_indent=indent).split('\n'))
    return '\n'.join(out)


def wrap(path):
    with open(path, encoding='utf-8') as f:
        text = f.read()
    with open(path, 'w', encoding='utf-8') as f:
        f.write(wrap_text(text))


def main(argv):
    if len(argv) >= 2 and argv[1] == '--check':
        problems = check()
        for p in problems:
            print(p)
        print('infra index: %s' % ('ok' if not problems else '%d problem(s)' % len(problems)))
        return 1 if problems else 0
    if len(argv) >= 2 and argv[1] == '--write':
        problems = write()
        for p in problems:
            print(p)
        print('index written; %d problem(s)' % len(problems))
        return 1 if problems else 0
    if len(argv) == 3 and argv[1] == '--wrap':
        wrap(argv[2])
        return 0
    print(__doc__)
    return 2


if __name__ == '__main__':
    sys.exit(main(sys.argv))
