#!/usr/bin/env python3
"""Verify that every internal link and anchor on the site resolves.

Scans every *.html in the repo root for href/src values, checks that each
internal target exists on disk, and checks that each #fragment points at a
real id in its target page. External http(s) links are not checked here
(curl them by hand when auditing; bot-blocking makes automation noisy).

Run: python linkcheck.py   (or: make check)
Exits nonzero listing every missing target with its referring pages, so a
build that leaves a page linking at nothing fails loudly instead of
shipping a 404. Added after Rule_of_St_Benedict.pdf and
Conferences_on_Prayer.pdf shipped as dead links in July 2026.
"""
import collections
import glob
import os
import re
import sys
import urllib.parse

# This script lives in scripts/; the built site to scan is docs/ off the repo
# root (one level up). chdir there so the *.html glob and relative link
# resolution below run against the served tree.
os.chdir(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'docs'))

# What the build publishes to R2. Regenerated by `make pdf-manifest`; a .pdf
# href naming anything absent from this list is a dead link exactly as before.
try:
    with open("pdfs.txt", encoding="utf-8") as _f:
        PUBLISHED_PDFS = {ln.strip() for ln in _f if ln.strip()}
except OSError:
    PUBLISHED_PDFS = set()

missing_pdfs = collections.defaultdict(set)   # pdf name -> referring pages
refs = collections.defaultdict(set)   # target file -> referring pages
frags = collections.defaultdict(set)  # (target file, fragment) -> referrers

for page in sorted(glob.glob("*.html")):
    html = open(page, encoding="utf-8", errors="replace").read()
    for m in re.finditer(r'(?:href|src)\s*=\s*["\']([^"\']+)["\']', html):
        url = m.group(1)
        if url.startswith(("http://", "https://", "mailto:", "data:",
                           "javascript:")):
            continue
        base, _, frag = url.partition("#")
        base = base.partition("?")[0]   # a cache-busting ?v=NN is not part of the on-disk path
        # The published PDFs moved to R2 (files.merecatholicity.com) in
        # September 2026 to keep the Pages site under its 1 GB limit — 244 files
        # and 293 MB of the 621 MB it had reached. Their site URLs still work:
        # a Cloudflare redirect rule maps /X.pdf to the bucket, so nothing that
        # was ever linked or shared breaks.
        #
        # They are no longer files on disk, so "does this exist" cannot be
        # answered by looking. Simply skipping them would have quietly retired
        # the very check this script was written for — two PDFs shipped as dead
        # links in July 2026 — so they are checked against pdfs.txt, the list of
        # what the build actually publishes.
        if base.endswith(".pdf"):
            if os.path.basename(base) not in PUBLISHED_PDFS:
                missing_pdfs[os.path.basename(base)].add(page)
            continue
        if base:
            refs[urllib.parse.unquote(base)].add(page)
        if frag:
            target = urllib.parse.unquote(base) if base else page
            frags[(target, frag)].add(page)

failures = []

for name in sorted(missing_pdfs):
    failures.append(
        f"unpublished PDF: {name}  <- " + ", ".join(sorted(missing_pdfs[name]))
        + "  (not in docs/pdfs.txt; run `make pdf-manifest` if it is newly built)")

for target in sorted(refs):
    if not os.path.exists(target):
        failures.append(
            f"missing file: {target}  <- " + ", ".join(sorted(refs[target])))

ids = {}
for (target, frag), pages in sorted(frags.items()):
    if not target.endswith(".html") or not os.path.exists(target):
        continue
    if target not in ids:
        h = open(target, encoding="utf-8", errors="replace").read()
        ids[target] = set(re.findall(r'(?:id|name)\s*=\s*["\']([^"\']+)["\']', h))
    if frag not in ids[target]:
        failures.append(
            f"missing anchor: {target}#{frag}  <- " + ", ".join(sorted(pages)))

if failures:
    print(f"linkcheck: {len(failures)} broken reference(s):")
    for f in failures:
        print(" ", f)
    sys.exit(1)

print(f"linkcheck: OK, {len(refs)} internal targets, {len(PUBLISHED_PDFS)} published PDFs "
      f"and {len(frags)} anchors verified across {len(glob.glob('*.html'))} pages")
